http=com.fyfe.factoryMethod.resourceFactory.impl.HttpResourceLoader
file=com.fyfe.factoryMethod.resourceFactory.impl.FileResourceLoader
classpath=com.fyfe.factoryMethod.resourceFactory.impl.ClassPathResourceLoader
default=com.fyfe.factoryMethod.resourceFactory.impl.DefaultResourceLoader