http=com.fyfe.factoryMethod2.resourceFactory.impl.HttpResourceLoader
file=com.fyfe.factoryMethod2.resourceFactory.impl.FileResourceLoader
classpath=com.fyfe.factoryMethod2.resourceFactory.impl.ClassPathResourceLoader
default=com.fyfe.factoryMethod2.resourceFactory.impl.DefaultResourceLoader
ftp=com.fyfe.factoryMethod2.resourceFactory.impl.FtpResourceLoader